### ISSUE TITLE
Uncaught ReferenceError: Foundation is not defined

### ISSUE THREAD

**Issue by arifhussain353** [zurb/joyride#225]
I include `foundation.joyride.js` script tag after jquery `3.1.1` but it through error  `Uncaught ReferenceError: Foundation is not defined`.I am not using `foundation`.Is it not work with  `JQuery` ? Or  is there issue with `JQuery version` ?
Sequence of files included : 
```javascript
      <link rel=" stylesheet" type="text/css" href="{{ URL::to('no_package_manger/joyride/dist/foundation.joyride.min.css')}}">
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.js"></script>
   <script src="{{ URL::to('no_package_manger/joyride/dist/foundation.joyride.min.js')}}"></script>
```
I download files from [here](http://zurb.com/playground/jquery-joyride-feature-tour-plugin)

**Comment by Owlbertz** [comment]
Hi @arifhussain353,
you downloaded the (old) version 2 of Joyride, which needs jQuery as well as Foundation for sites in order to run.
The latest version 3 of Joyride also has a standalone version (without the need to include Foundation), which you can find [in the dist folder of this repository](https://github.com/zurb/joyride/tree/master/dist).
You can have a look on version 3 on the [Joyride demo page](http://zurb.github.io/joyride/).

**Comment by arifhussain353** [comment]
@Owlbertz  Thank you .
